name: Docker Image CD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA3DBFS6WPMRFX4T67
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Login to ECR
      run: aws ecr-public get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin public.ecr.aws/g7k2b4t7

    - name: Build, tag and push the Docker image
      run: | 
        docker build . -t dkassay/continuous_php_image
        docker tag dkassay/continuous_php_image:latest public.ecr.aws/g7k2b4t7/dkassay/continuous_php_image:latest
        docker push public.ecr.aws/g7k2b4t7/dkassay/continuous_php_image:latest
